"""Initial migration

Revision ID: d4d50337fec5
Revises: 
Create Date: 2024-01-22 15:58:16.418020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d50337fec5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine_exercises')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_index('idx_exercises_exercise_name')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index('idx_logs_date')
        batch_op.drop_index('idx_logs_user_routine_exercise')

    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_index('idx_routines_user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_email')

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index('idx_workouts_routine_exercise')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index('idx_workouts_routine_exercise', ['routine_id', 'exercise_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)

    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.create_index('idx_routines_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index('idx_logs_user_routine_exercise', ['user_id', 'routine_id', 'exercise_id'], unique=False)
        batch_op.create_index('idx_logs_date', ['date'], unique=False)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_exercises_exercise_name', ['exercise_name'], unique=False)
        batch_op.drop_column('user_id')

    op.create_table('routine_exercises',
    sa.Column('routine_id', sa.INTEGER(), nullable=True),
    sa.Column('exercise_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.routine_id'], )
    )
    # ### end Alembic commands ###
